run:
  concurrency: 4
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  go: '1.24'

linters:
  enable:
    - gosec
    - gci

issues:
  new: true
  exclude-rules:

    - path: main.go
      linters:
        - gci

    - path: geoip/geoip.go
      linters:
        - gosec
